# global:
#   scrape_interval: 15s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - "alertmanager:9093"
# rule_files:
#   - "alert_rules.yml"

# scrape_configs:
#   - job_name: "nginx-exporter"
#     static_configs:
#       - targets: ["nginx-exporter:9113"]

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"
